name: Build wbn

on: 
  push:
  pull_request:
  schedule:
  - cron: "* * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
#     permissions:
#       contents: write

    steps:
  # You may pin to the exact commit or the version.
  # uses: tvdias/github-tagger@ed7350546e3e503b5e942dffd65bc8751a95e49d
    - uses: actions/checkout@v2
    - uses: tvdias/github-tagger@v0.0.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # The GITHUB_TOKEN secret
        # Tag text
        tag: Build
        # optional commit sha to apply the tag to
    - uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: TurboWarp/scratch-gui
        platform: github
        path: turbowarp/
    - run: |
        # make file runnable, might not be necessary
        chmod +x "${GITHUB_WORKSPACE}/build.sh"

        # run script
        "${GITHUB_WORKSPACE}/build.sh"
        # or
        # "${{ format('{0}/.github/script.sh', github.workspace) }}"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.wbn,turbowarp.tar.gz"
        omitBody: true
        allowUpdates: true
        tag: Build
        token: ${{ secrets.GITHUB_TOKEN }}
